apiVersion: apps/v1
kind: Deployment
metadata:
  name: precedentia-summary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary
  template:
    metadata:
      labels:
        app: summary
    spec:
      containers:
      - name: summary

        image: docker.io/gabguimaraes/precedentia-summary:067fb7d

        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

