name: CD Pipeline

on:
  push:
    branches:
      - hml

jobs:
  build-and-update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="gabguimaraes/precedentia-summary"
          docker build -t $IMAGE_NAME:$SHA_TAG .
          docker push $IMAGE_NAME:$SHA_TAG

      - name: Update ArgoCD Manifests
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/FR0M-ZER0/PrecedentIA.git
          cd PrecedentIA
          IMAGE_NAME="gabguimaraes/precedentia-summary"
          sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$SHA_TAG|g" precedentia-summary/k8s/deployment.yaml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add precedentia-summary/k8s/deployment.yaml
          git commit -m "CD: Update precedentia-summary image tag to $SHA_TAG"
          git push